// Dependências necessárias:
// npm install express prom-client

const express = require('express');
const client = require('prom-client');
const path = require('path');

const app = express();

// O prom-client registra métricas padrão do processo Node e as métricas customizadas.

client.collectDefaultMetrics({ prefix: 'app_' });

const httpRequestsTotal = new client.Counter({
	name: 'http_requests_total',
	help: 'Total HTTP requests',
	labelNames: ['method', 'route', 'status']
});

const httpRequestDuration = new client.Histogram({
	name: 'http_request_duration_seconds',
	help: 'HTTP request duration in seconds',
	labelNames: ['method', 'route', 'status'],
	buckets: [0.005, 0.01, 0.05, 0.1, 0.5, 1, 2, 5]
});

const appErrors = new client.Counter({
	name: 'app_errors_total',
	help: 'Total error responses generated by the application'
});

const loginFailures = new client.Counter({
	name: 'login_failures_total',
	help: 'Total login failures',
	labelNames: ['reason']
});

const usersGauge = new client.Gauge({
	name: 'app_users_total',
	help: 'Number of registered users'
});

const errorRateGauge = new client.Gauge({
	name: 'app_error_rate_percent',
	help: 'Percentage of requests that ended in error over the last minute'
});

const errorsPerMinuteGauge = new client.Gauge({
	name: 'app_errors_per_minute',
	help: 'Number of error responses seen in the last minute'
});

const loginIncidentGauge = new client.Gauge({
	name: 'app_login_failure_incident_active',
	help: 'Whether the forced login failure incident is active'
});

const latencyIncidentGauge = new client.Gauge({
	name: 'app_latency_incident_active',
	help: 'Whether the latency incident is active'
});

const simulateLoadRuns = new client.Counter({
	name: 'simulate_load_runs_total',
	help: 'Number of times the load simulator was invoked'
});

const simulateLoadIterations = new client.Counter({
	name: 'simulate_load_iterations_total',
	help: 'Total iterations executed by the load simulator'
});

// Base em memória para o CRUD de usuários.
const users = [];
let nextId = 1;

// Estado dos incidentes simulados. Essas flags alteram o comportamento da API.
const incidentState = {
	loginFailureEnabled: false,
	latencyEnabled: false,
	latencyDelayMs: 1500,
	latencyJitterMs: 500,
	latencyFailureRatePercent: 20,
	latencyFailureStatus: 503
};

// Janelas móveis para calcular erros por minuto e taxa de erro.
const requestTimestamps = [];
const errorTimestamps = [];

usersGauge.set(0);
loginIncidentGauge.set(0);
latencyIncidentGauge.set(0);

// Garante que números vindos da query/body fiquem dentro de uma faixa segura.
function clampNumber(value, fallback, min, max) {
	const parsed = Number(value);
	if (!Number.isFinite(parsed)) {
		return fallback;
	}
	return Math.min(max, Math.max(min, parsed));
}

// Aceita vários formatos comuns para booleanos em payloads e query params.
function parseBoolean(value, fallback = false) {
	if (value === undefined || value === null) {
		return fallback;
	}
	if (typeof value === 'boolean') {
		return value;
	}
	if (typeof value === 'string') {
		const normalized = value.trim().toLowerCase();
		if (['true', '1', 'yes', 'on'].includes(normalized)) {
			return true;
		}
		if (['false', '0', 'no', 'off'].includes(normalized)) {
			return false;
		}
	}
	return Boolean(value);
}

// Normaliza o nome da rota para uso nas métricas.
function routeLabel(req) {
	if (req.route && req.route.path) {
		const routePath = Array.isArray(req.route.path) ? req.route.path[0] : req.route.path;
		return `${req.baseUrl || ''}${routePath}`;
	}
	return req.originalUrl ? req.originalUrl.split('?')[0] : req.path;
}

// Remove eventos antigos da janela de 1 minuto.
function trimWindow(now = Date.now()) {
	const cutoff = now - 60000;
	while (requestTimestamps.length > 0 && requestTimestamps[0] < cutoff) {
		requestTimestamps.shift();
	}
	while (errorTimestamps.length > 0 && errorTimestamps[0] < cutoff) {
		errorTimestamps.shift();
	}
}

// Atualiza as métricas derivadas com base nos eventos recentes.
function updateDerivedMetrics(now = Date.now()) {
	trimWindow(now);
	const requestsLastMinute = requestTimestamps.length;
	const errorsLastMinute = errorTimestamps.length;
	errorsPerMinuteGauge.set(errorsLastMinute);
	errorRateGauge.set(requestsLastMinute > 0 ? (errorsLastMinute / requestsLastMinute) * 100 : 0);
}

// Registra um erro na janela móvel e recalcula os indicadores derivados.
function recordError(now = Date.now()) {
	appErrors.inc();
	errorTimestamps.push(now);
	updateDerivedMetrics(now);
}

// Não aplicamos latência artificial em rotas operacionais ou internas.
function shouldBypassLatency(req) {
	const pathName = req.path || '';
	return pathName === '/metrics' || pathName === '/simulate-load' || pathName === '/simulate-error' || pathName.startsWith('/internal/incidents');
}

// Calcula um delay artificial com jitter para simular instabilidade.
function computeLatencyDelay() {
	const jitter = incidentState.latencyJitterMs > 0 ? Math.floor((Math.random() * 2 - 1) * incidentState.latencyJitterMs) : 0;
	return Math.max(0, incidentState.latencyDelayMs + jitter);
}

// Middleware de finalização: mede duração, conta requisições e escreve log da resposta.
function applyResponseMetrics(req, res, startedAt) {
	const durationSeconds = Number(process.hrtime.bigint() - startedAt) / 1e9;
	const statusCode = res.statusCode;
	const route = routeLabel(req);

	httpRequestDuration.labels(req.method, route, String(statusCode)).observe(durationSeconds);
	httpRequestsTotal.labels(req.method, route, String(statusCode)).inc();

	const completedAt = Date.now();
	requestTimestamps.push(completedAt);
	if (statusCode >= 400) {
		recordError(completedAt);
	} else {
		updateDerivedMetrics(completedAt);
	}

	console.log(JSON.stringify({
		level: 'info',
		event: 'request_completed',
		method: req.method,
		route,
		status: statusCode,
		duration_ms: Number((durationSeconds * 1000).toFixed(2))
	}));
}

// Captura o tempo total de cada requisição e agenda a gravação das métricas ao final.
app.use((req, res, next) => {
	const startedAt = process.hrtime.bigint();
	res.on('finish', () => applyResponseMetrics(req, res, startedAt));
	next();
});

// Parser de JSON para POST/PUT e arquivos estáticos do front simples.
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// Middleware de latência: se o incidente estiver ativo, atrasa a resposta e pode falhar.
app.use((req, res, next) => {
	if (!incidentState.latencyEnabled || shouldBypassLatency(req)) {
		return next();
	}

	const delayMs = computeLatencyDelay();
	setTimeout(() => {
		const failureRate = incidentState.latencyFailureRatePercent / 100;
		if (Math.random() < failureRate) {
			console.error(JSON.stringify({
				level: 'error',
				event: 'latency_incident_failure',
				method: req.method,
				path: req.originalUrl,
				delay_ms: delayMs,
				status: incidentState.latencyFailureStatus
			}));
			return res.status(incidentState.latencyFailureStatus).json({ error: 'artificial latency failure' });
		}

		return next();
	}, delayMs);
});

// Cria um usuário em memória e registra o evento em log.
app.post('/register', (req, res) => {
	const username = typeof req.body?.username === 'string' ? req.body.username.trim() : '';
	const password = typeof req.body?.password === 'string' ? req.body.password : '';

	if (!username || !password) {
		console.error(JSON.stringify({ level: 'error', event: 'register_failed', reason: 'missing_fields' }));
		return res.status(400).json({ error: 'username and password required' });
	}

	if (users.some((user) => user.username === username)) {
		console.error(JSON.stringify({ level: 'error', event: 'register_failed', reason: 'already_exists', user: username }));
		return res.status(409).json({ error: 'user already exists' });
	}

	const user = { id: nextId++, username, password };
	users.push(user);
	usersGauge.set(users.length);
	console.log(JSON.stringify({ level: 'info', event: 'user_registered', user: username }));
	return res.status(201).json({ id: user.id, username: user.username });
});

// Autenticação simples. Quando o incidente está ativo, devolve 500 de forma proposital.
app.post('/login', (req, res) => {
	const username = typeof req.body?.username === 'string' ? req.body.username.trim() : '';
	const password = typeof req.body?.password === 'string' ? req.body.password : '';

	if (incidentState.loginFailureEnabled) {
		loginFailures.inc({ reason: 'incident_active' });
		console.error(JSON.stringify({ level: 'error', event: 'login_failed', reason: 'incident_active', user: username }));
		return res.status(500).json({ success: false, error: 'login incident active' });
	}

	const user = users.find((candidate) => candidate.username === username && candidate.password === password);
	if (!user) {
		loginFailures.inc({ reason: 'invalid_credentials' });
		console.error(JSON.stringify({ level: 'error', event: 'login_failed', reason: 'invalid_credentials', user: username }));
		return res.status(401).json({ success: false, error: 'invalid credentials' });
	}

	console.log(JSON.stringify({ level: 'info', event: 'login_success', user: username }));
	return res.json({ success: true });
});

// Lista os usuários sem expor a senha.
app.get('/users', (req, res) => {
	const cleanUsers = users.map((user) => ({ id: user.id, username: user.username }));
	return res.json(cleanUsers);
});

// Atualiza username e/ou password de um usuário existente.
app.put('/users/:id', (req, res) => {
	const id = Number(req.params.id);
	const username = typeof req.body?.username === 'string' ? req.body.username.trim() : '';
	const password = typeof req.body?.password === 'string' ? req.body.password : '';
	const user = users.find((candidate) => candidate.id === id);

	if (!user) {
		return res.status(404).json({ error: 'not found' });
	}

	if (username && users.some((candidate) => candidate.username === username && candidate.id !== id)) {
		console.error(JSON.stringify({ level: 'error', event: 'update_failed', reason: 'already_exists', user: username }));
		return res.status(409).json({ error: 'user already exists' });
	}

	if (username) {
		user.username = username;
	}
	if (password) {
		user.password = password;
	}

	console.log(JSON.stringify({ level: 'info', event: 'user_updated', id: user.id, username: user.username }));
	return res.json({ id: user.id, username: user.username });
});

// Remove um usuário da lista em memória.
app.delete('/users/:id', (req, res) => {
	const id = Number(req.params.id);
	const before = users.length;
	const remainingUsers = users.filter((user) => user.id !== id);

	if (remainingUsers.length === before) {
		return res.status(404).json({ error: 'not found' });
	}

	users.length = 0;
	users.push(...remainingUsers);
	usersGauge.set(users.length);
	console.log(JSON.stringify({ level: 'info', event: 'user_deleted', id }));
	return res.status(204).end();
});

// Endpoint para gerar pico de CPU com cálculos intensivos.
app.get('/simulate-load', (req, res) => {
	const iterations = clampNumber(req.query.iterations, 5000000, 1000, 50000000);
	const seed = Date.now();
	let checksum = 0;

	simulateLoadRuns.inc();
	simulateLoadIterations.inc(iterations);

	for (let index = 0; index < iterations; index += 1) {
		checksum += Math.sqrt((index + seed) % 1000) * Math.sqrt((index % 97) + 1);
	}

	console.log(JSON.stringify({
		level: 'info',
		event: 'simulate_load_completed',
		iterations,
		checksum: Number(checksum.toFixed(2))
	}));

	return res.json({
		success: true,
		iterations,
		checksum: Number(checksum.toFixed(2))
	});
});

// Endpoint auxiliar para forçar uma exceção não tratada e testar o middleware de erro.
app.get('/simulate-error', (req, res) => {
	throw new Error('simulated unexpected failure');
});

// Liga ou desliga o incidente que faz o login falhar com erro 500.
app.post('/internal/incidents/login-failure', (req, res) => {
	incidentState.loginFailureEnabled = parseBoolean(req.body?.enabled, !incidentState.loginFailureEnabled);
	loginIncidentGauge.set(incidentState.loginFailureEnabled ? 1 : 0);

	console.log(JSON.stringify({
		level: 'info',
		event: 'incident_login_failure_updated',
		enabled: incidentState.loginFailureEnabled
	}));

	return res.json({
		enabled: incidentState.loginFailureEnabled
	});
});

// Liga ou desliga o incidente de latência e ajusta delay, jitter e taxa de falha.
app.post('/internal/incidents/latency', (req, res) => {
	incidentState.latencyEnabled = parseBoolean(req.body?.enabled, !incidentState.latencyEnabled);
	incidentState.latencyDelayMs = clampNumber(req.body?.delayMs, incidentState.latencyDelayMs, 0, 60000);
	incidentState.latencyJitterMs = clampNumber(req.body?.jitterMs, incidentState.latencyJitterMs, 0, 30000);
	incidentState.latencyFailureRatePercent = clampNumber(req.body?.failureRatePercent, incidentState.latencyFailureRatePercent, 0, 100);
	incidentState.latencyFailureStatus = clampNumber(req.body?.statusCode, incidentState.latencyFailureStatus, 500, 599);
	latencyIncidentGauge.set(incidentState.latencyEnabled ? 1 : 0);

	console.log(JSON.stringify({
		level: 'info',
		event: 'incident_latency_updated',
		enabled: incidentState.latencyEnabled,
		delay_ms: incidentState.latencyDelayMs,
		jitter_ms: incidentState.latencyJitterMs,
		failure_rate_percent: incidentState.latencyFailureRatePercent,
		failure_status: incidentState.latencyFailureStatus
	}));

	return res.json({
		enabled: incidentState.latencyEnabled,
		delayMs: incidentState.latencyDelayMs,
		jitterMs: incidentState.latencyJitterMs,
		failureRatePercent: incidentState.latencyFailureRatePercent,
		failureStatus: incidentState.latencyFailureStatus
	});
});

// Restaura o comportamento normal da aplicação após testes de incidente.
app.post('/internal/incidents/reset', (req, res) => {
	incidentState.loginFailureEnabled = false;
	incidentState.latencyEnabled = false;
	incidentState.latencyDelayMs = 1500;
	incidentState.latencyJitterMs = 500;
	incidentState.latencyFailureRatePercent = 20;
	incidentState.latencyFailureStatus = 503;
	loginIncidentGauge.set(0);
	latencyIncidentGauge.set(0);

	console.log(JSON.stringify({ level: 'info', event: 'incidents_reset' }));
	return res.json({ success: true });
});

// Endpoint que o Prometheus coleta para ler as métricas da aplicação.
app.get('/metrics', async (req, res) => {
	try {
		updateDerivedMetrics();
		res.set('Content-Type', client.register.contentType);
		return res.end(await client.register.metrics());
	} catch (error) {
		console.error(JSON.stringify({ level: 'error', event: 'metrics_error', message: error.message }));
		return res.status(500).end(error.message);
	}
});

// Tratamento central de erros para garantir log estruturado e resposta 500.
app.use((error, req, res, next) => {
	console.error(JSON.stringify({
		level: 'error',
		event: 'application_exception',
		method: req.method,
		path: req.originalUrl,
		message: error.message,
		stack: error.stack
	}));

	if (res.headersSent) {
		return next(error);
	}

	return res.status(500).json({ error: 'internal server error' });
});

// Eventos globais do Node para falhas assíncronas ou exceções fatais.
process.on('unhandledRejection', (reason) => {
	const message = reason && reason.message ? reason.message : String(reason);
	console.error(JSON.stringify({ level: 'error', event: 'unhandled_rejection', message }));
});

process.on('uncaughtException', (error) => {
	console.error(JSON.stringify({ level: 'error', event: 'uncaught_exception', message: error.message, stack: error.stack }));
});

// Ruído periódico para o laboratório de observabilidade observar logs recorrentes.
setInterval(() => {
	console.log(JSON.stringify({ level: 'info', event: 'heartbeat', msg: 'periodic heartbeat' }));
	console.error(JSON.stringify({ level: 'error', event: 'periodic_error', msg: 'periodic synthetic error' }));
}, 5000);

const DEFAULT_PORT = 3000;
const requestedPort = Number(process.env.PORT) || DEFAULT_PORT;

// Sobe o servidor e, se a porta padrão estiver ocupada, tenta a próxima disponível.
function startServer(port) {
	const server = app.listen(port, () => {
		const appUrl = `http://localhost:${port}`;
		console.log(JSON.stringify({
			level: 'info',
			event: 'server_started',
			port,
			url: appUrl,
			login_failure_incident: incidentState.loginFailureEnabled,
			latency_incident: incidentState.latencyEnabled
		}));
		console.log(`Application is up at ${appUrl}`);
	});

	server.on('error', (error) => {
		if (error.code === 'EADDRINUSE' && !process.env.PORT) {
			const nextPort = port + 1;
			console.error(JSON.stringify({
				level: 'error',
				event: 'port_in_use_retry',
				message: `Port ${port} busy, retrying on ${nextPort}`
			}));
			startServer(nextPort);
			return;
		}

		console.error(JSON.stringify({
			level: 'error',
			event: 'server_start_failed',
			port,
			message: error.message
		}));
		process.exitCode = 1;
	});
}

startServer(requestedPort);
